development:
  password: shptka_5ab341db2922c437c15b5859aaba75da
  theme_id: 128947978425
  store: maj-development-1.myshopify.com
  directory: src/theme
  ignore_files:
  - src/config/settings_data.json
  - config/settings_data.json
  - src/locales/*.json
  - locales/*.json











